project:
  type: website
  output-dir: docs

website:
  title: "Eli Lewis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd # my new navbar page

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

