project:
  type: website
  output-dir: docs

website:
  title: "Eli Lewis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- resources.qmd # my new navbar page
      #- href: blog.qmd
      #  text: Blog
      - href: photography.qmd
        text: Photography

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

